<a href="https://colab.research.google.com/github/nafis-saad/Assignments/blob/main/Copy_of_Main_Bikeshare_do_not_touch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_json("/content/drive/MyDrive/Tweetpy/Twitter_EVs_2020-01.json", encoding ='utf-8')

In [ ]:
#import json
#import csv
#from google.colab import files
##uploaded = files.upload()

In [ ]:
#uploaded["Twitter_EVs_2020-01.json"].decode("utf-8").split("\r\n")

# User **Location**

In [ ]:
with pd.option_context('display.max_colwidth', None):
  print(df["user"][6])

{'created_at': '2013-10-14T06:14:07.000Z', 'description': 'Democrat in OK. Supporter of universal healthcare, combating climate change, comprehensive immigration reform, & all things that make us a better country.', 'id': '1960044362', 'name': 'Sarah', 'profile_image_url': 'https://pbs.twimg.com/profile_images/611075059860398080/UYL_KAm4_normal.jpg', 'public_metrics': {'followers_count': 122, 'following_count': 1280, 'listed_count': 1, 'tweet_count': 67203}, 'username': 'sbclifton77', 'verified': False}

In [ ]:
df

,author_id,conversation_id,created_at,edit_history_tweet_ids,entities,id,lang,public_metrics,text,user,in_reply_to_user_id,referenced_tweets,retweeted_status,geo,twitter_places,attachments,withheld
0,22788836,1223395490366025728,2020-01-31 23:59:49+00:00,[1223395490366025728],"{'annotations': [{'end': 7, 'normalized_text':...",1223395490366025728,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Alonso L is starting a bike ride and you can t...,"{'created_at': '2009-03-04T15:44:31.000Z', 'de...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3157671046,1223383749263593472,2020-01-31 23:59:11+00:00,[1223395330974191617],"{'mentions': [{'end': 12, 'id': '23829152', 's...",1223395330974191616,en,"{'impression_count': 0, 'like_count': 1, 'quot...","@BoycottsBat Few of my mates agree, got to tal...","{'created_at': '2015-04-11T20:24:00.000Z', 'de...",23829152.0,"[{'id': '1223387698720911360', 'type': 'replie...","{'author_id': '23829152', 'conversation_id': '...",NaN,NaN,NaN,NaN
2,181634813,1223394798876479488,2020-01-31 23:57:04+00:00,[1223394798876479489],"{'annotations': [{'end': 71, 'normalized_text'...",1223394798876479488,en,"{'impression_count': 0, 'like_count': 7, 'quot...",My mamba mentality just got me through a 3 mil...,"{'created_at': '2010-08-22T18:02:25.000Z', 'de...",NaN,NaN,NaN,{'place_id': '488da0de4c92ac8e'},"{'country': 'United States', 'full_name': 'Pla...",NaN,NaN
3,1633428576,1223394344545275904,2020-01-31 23:55:15+00:00,[1223394344545275905],"{'annotations': [{'end': 40, 'normalized_text'...",1223394344545275904,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @BillyCorben: TONIGHT #SuperBowl Miami traf...,"{'created_at': '2013-07-30T17:45:37.000Z', 'de...",NaN,"[{'id': '1223335486007148546', 'type': 'retwee...",{'attachments': {'media_keys': ['3_12233354821...,NaN,NaN,NaN,NaN
4,1225992186,1223358325452087296,2020-01-31 23:55:10+00:00,[1223394321560244224],"{'mentions': [{'end': 15, 'id': '58885604', 's...",1223394321560244224,en,"{'impression_count': 0, 'like_count': 0, 'quot...",@originaltomtom @sibilia_ralph @AMarch4OurLive...,"{'created_at': '2013-02-27T20:40:54.000Z', 'de...",58885604.0,"[{'id': '1223392333502218240', 'type': 'replie...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27263,2612253354,1212163653568540672,2020-01-01 00:08:30+00:00,[1212163653568540674],"{'annotations': [{'end': 83, 'normalized_text'...",1212163653568540672,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @SoBiHamilton: Together we have ridden over...,"{'created_at': '2014-07-08T20:20:50.000Z', 'de...",NaN,"[{'id': '1212035371808305153', 'type': 'retwee...","{'author_id': '2301638287', 'conversation_id':...",NaN,NaN,NaN,NaN
27264,2221442917,1212163086624247808,2020-01-01 00:06:15+00:00,[1212163086624247808],{'urls': [{'display_url': 'pic.twitter.com/rKr...,1212163086624247808,en,"{'impression_count': 0, 'like_count': 0, 'quot...",üòçüòçüòçüòç2‚É£0‚É£2‚É£0‚É£ first bike ride https://t.co/rKrK...,"{'created_at': '2013-11-29T13:26:39.000Z', 'de...",NaN,NaN,NaN,{'place_id': '2a3a6daaec3b0848'},"{'country': 'India', 'full_name': 'Sholinganal...",{'media_keys': ['7_1212163009256124416']},NaN
27265,114743976,1212161757105577984,2020-01-01 00:00:58+00:00,[1212161757105577986],"{'annotations': [{'end': 77, 'normalized_text'...",1212161757105577984,en,"{'impression_count': 0, 'like_count': 1, 'quot...",Should of gone out for a bike ride in the dark...,"{'created_at': '2010-02-16T13:29:12.000Z', 'de...",NaN,NaN,NaN,NaN,NaN,{'media_keys': ['3_1212161747362168832']},NaN
27266,3279247754,1212161708803801088,2020-01-01 00:00:46+00:00,[1212161708803801089],"{'mentions': [{'end': 16, 'id': '1075134579214...",1212161708803801088,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @DomLadMaster: Happy Friday everyone!\n\nTi...,"{'created_at': '2015-07-14T05:22:07.000Z', 'de...",NaN,"[{'id': '1164887035653566464', 'type': 'retwee...",{'attachments': {'media_keys': ['3_11648870285...,NaN,NaN,NaN,NaN
27267,2491046567,1212161581670391808,2020-01-01 00:00:16+00:00,[1212161581670391809],"{'annotations': [{'end': 7, 'normalized_text':...",1212161581670391808,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Brooklyn gets first public bike parking hub - ...,"{'created_at': '2014-04-18T01:39:46.000Z', 'de...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
n = df.shape[0]
print(n)
df["user_location"]= "NaN"
for i in range(n):
  if 'location' in df['user'][i]:
    #df["nafis"][i]= df["user"][i]['location']
    df["user_location"][i]=  df["user"][i]['location']

    #print(df1)

27268

<ipython-input-8-24c22de337d8>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["user_location"][i]=  df["user"][i]['location']

In [ ]:
print(df.head())

    author_id      conversation_id                created_at  \
0    22788836  1223395490366025728 2020-01-31 23:59:49+00:00
1  3157671046  1223383749263593472 2020-01-31 23:59:11+00:00
2   181634813  1223394798876479488 2020-01-31 23:57:04+00:00
3  1633428576  1223394344545275904 2020-01-31 23:55:15+00:00
4  1225992186  1223358325452087296 2020-01-31 23:55:10+00:00

  edit_history_tweet_ids                                           entities  \
0  [1223395490366025728]  {'annotations': [{'end': 7, 'normalized_text':...
1  [1223395330974191617]  {'mentions': [{'end': 12, 'id': '23829152', 's...
2  [1223394798876479489]  {'annotations': [{'end': 71, 'normalized_text'...
3  [1223394344545275905]  {'annotations': [{'end': 40, 'normalized_text'...
4  [1223394321560244224]  {'mentions': [{'end': 15, 'id': '58885604', 's...

                    id lang  \
0  1223395490366025728   en
1  1223395330974191616   en
2  1223394798876479488   en
3  1223394344545275904   en
4  1223394321560244224   en

                                      public_metrics  \
0  {'impression_count': 0, 'like_count': 0, 'quot...
1  {'impression_count': 0, 'like_count': 1, 'quot...
2  {'impression_count': 0, 'like_count': 7, 'quot...
3  {'impression_count': 0, 'like_count': 0, 'quot...
4  {'impression_count': 0, 'like_count': 0, 'quot...

                                                text  \
0  Alonso L is starting a bike ride and you can t...
1  @BoycottsBat Few of my mates agree, got to tal...
2  My mamba mentality just got me through a 3 mil...
3  RT @BillyCorben: TONIGHT #SuperBowl Miami traf...
4  @originaltomtom @sibilia_ralph @AMarch4OurLive...

                                                user  in_reply_to_user_id  \
0  {'created_at': '2009-03-04T15:44:31.000Z', 'de...                  NaN
1  {'created_at': '2015-04-11T20:24:00.000Z', 'de...           23829152.0
2  {'created_at': '2010-08-22T18:02:25.000Z', 'de...                  NaN
3  {'created_at': '2013-07-30T17:45:37.000Z', 'de...                  NaN
4  {'created_at': '2013-02-27T20:40:54.000Z', 'de...           58885604.0

                                   referenced_tweets  \
0                                                NaN
1  [{'id': '1223387698720911360', 'type': 'replie...
2                                                NaN
3  [{'id': '1223335486007148546', 'type': 'retwee...
4  [{'id': '1223392333502218240', 'type': 'replie...

                                    retweeted_status  \
0                                                NaN
1  {'author_id': '23829152', 'conversation_id': '...
2                                                NaN
3  {'attachments': {'media_keys': ['3_12233354821...
4                                                NaN

                                geo  \
0                               NaN
1                               NaN
2  {'place_id': '488da0de4c92ac8e'}
3                               NaN
4                               NaN

                                      twitter_places attachments withheld  \
0                                                NaN         NaN      NaN
1                                                NaN         NaN      NaN
2  {'country': 'United States', 'full_name': 'Pla...         NaN      NaN
3                                                NaN         NaN      NaN
4                                                NaN         NaN      NaN

                    user_location
0           Auckland, New Zealand
1        Scotland, United Kingdom
2  Somewhere making it happen, TX
3              Coral Springs, FL
4        Innsmouth, Massachusetts

In [ ]:
df['user_location'].value_counts()

NaN                  5792
Washington, DC        261
Los Angeles, CA       235
London, England       221
Center Valley, PA     218
                     ...
srilanka                1
Southaven, MS           1
The TARDIS              1
sarasota fl             1
Patchogue, NY           1
Name: user_location, Length: 8156, dtype: int64

## ***Tweet_location***

In [ ]:
import re
i=0
df['twitter_places_nafis']="NaN"
for value in df['twitter_places']:
    if isinstance(value, dict):
      my_string = str(value)
      matches = re.findall(r'\[(.*?)\]', my_string)
      df['twitter_places_nafis'][i] = matches
      i += 1
    else:
      df['twitter_places_nafis'][i] = "NaN"
      i += 1

<ipython-input-11-3ee425d8dc57>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['twitter_places_nafis'][i] = "NaN"
<ipython-input-11-3ee425d8dc57>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['twitter_places_nafis'][i] = matches

In [ ]:
df['twitter_places_nafis']

0                                                    NaN
1                                                    NaN
2        [-96.85743, 32.9971507, -96.612371, 33.1253341]
3                                                    NaN
4                                                    NaN
                              ...
27263                                                NaN
27264       [80.056161, 12.850328, 80.268192, 13.028593]
27265                                                NaN
27266                                                NaN
27267                                                NaN
Name: twitter_places_nafis, Length: 27268, dtype: object

In [ ]:
df

,author_id,conversation_id,created_at,edit_history_tweet_ids,entities,id,lang,public_metrics,text,user,in_reply_to_user_id,referenced_tweets,retweeted_status,geo,twitter_places,attachments,withheld,user_location,twitter_places_nafis
0,22788836,1223395490366025728,2020-01-31 23:59:49+00:00,[1223395490366025728],"{'annotations': [{'end': 7, 'normalized_text':...",1223395490366025728,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Alonso L is starting a bike ride and you can t...,"{'created_at': '2009-03-04T15:44:31.000Z', 'de...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Auckland, New Zealand",NaN
1,3157671046,1223383749263593472,2020-01-31 23:59:11+00:00,[1223395330974191617],"{'mentions': [{'end': 12, 'id': '23829152', 's...",1223395330974191616,en,"{'impression_count': 0, 'like_count': 1, 'quot...","@BoycottsBat Few of my mates agree, got to tal...","{'created_at': '2015-04-11T20:24:00.000Z', 'de...",23829152.0,"[{'id': '1223387698720911360', 'type': 'replie...","{'author_id': '23829152', 'conversation_id': '...",NaN,NaN,NaN,NaN,"Scotland, United Kingdom",NaN
2,181634813,1223394798876479488,2020-01-31 23:57:04+00:00,[1223394798876479489],"{'annotations': [{'end': 71, 'normalized_text'...",1223394798876479488,en,"{'impression_count': 0, 'like_count': 7, 'quot...",My mamba mentality just got me through a 3 mil...,"{'created_at': '2010-08-22T18:02:25.000Z', 'de...",NaN,NaN,NaN,{'place_id': '488da0de4c92ac8e'},"{'country': 'United States', 'full_name': 'Pla...",NaN,NaN,"Somewhere making it happen, TX","[-96.85743, 32.9971507, -96.612371, 33.1253341]"
3,1633428576,1223394344545275904,2020-01-31 23:55:15+00:00,[1223394344545275905],"{'annotations': [{'end': 40, 'normalized_text'...",1223394344545275904,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @BillyCorben: TONIGHT #SuperBowl Miami traf...,"{'created_at': '2013-07-30T17:45:37.000Z', 'de...",NaN,"[{'id': '1223335486007148546', 'type': 'retwee...",{'attachments': {'media_keys': ['3_12233354821...,NaN,NaN,NaN,NaN,"Coral Springs, FL",NaN
4,1225992186,1223358325452087296,2020-01-31 23:55:10+00:00,[1223394321560244224],"{'mentions': [{'end': 15, 'id': '58885604', 's...",1223394321560244224,en,"{'impression_count': 0, 'like_count': 0, 'quot...",@originaltomtom @sibilia_ralph @AMarch4OurLive...,"{'created_at': '2013-02-27T20:40:54.000Z', 'de...",58885604.0,"[{'id': '1223392333502218240', 'type': 'replie...",NaN,NaN,NaN,NaN,NaN,"Innsmouth, Massachusetts",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27263,2612253354,1212163653568540672,2020-01-01 00:08:30+00:00,[1212163653568540674],"{'annotations': [{'end': 83, 'normalized_text'...",1212163653568540672,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @SoBiHamilton: Together we have ridden over...,"{'created_at': '2014-07-08T20:20:50.000Z', 'de...",NaN,"[{'id': '1212035371808305153', 'type': 'retwee...","{'author_id': '2301638287', 'conversation_id':...",NaN,NaN,NaN,NaN,"Hamilton, Ontario",NaN
27264,2221442917,1212163086624247808,2020-01-01 00:06:15+00:00,[1212163086624247808],{'urls': [{'display_url': 'pic.twitter.com/rKr...,1212163086624247808,en,"{'impression_count': 0, 'like_count': 0, 'quot...",üòçüòçüòçüòç2‚É£0‚É£2‚É£0‚É£ first bike ride https://t.co/rKrK...,"{'created_at': '2013-11-29T13:26:39.000Z', 'de...",NaN,NaN,NaN,{'place_id': '2a3a6daaec3b0848'},"{'country': 'India', 'full_name': 'Sholinganal...",{'media_keys': ['7_1212163009256124416']},NaN,NaN,"[80.056161, 12.850328, 80.268192, 13.028593]"
27265,114743976,1212161757105577984,2020-01-01 00:00:58+00:00,[1212161757105577986],"{'annotations': [{'end': 77, 'normalized_text'...",1212161757105577984,en,"{'impression_count': 0, 'like_count': 1, 'quot...",Should of gone out for a bike ride in the dark...,"{'created_at': '2010-02-16T13:29:12.000Z', 'de...",NaN,NaN,NaN,NaN,NaN,{'media_keys': ['3_1212161747362168832']},NaN,London Brighton Sussex UK,NaN
27266,3279247754,1212161708803801088,2020-01-01 00:00:46+00:00,[1212161708803801089],"{'mentions': [{'end': 16, 'id': '1075134579214...",1212161708803801088,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @DomLadMaster: Happy Friday everyone!\n\nTi...,"{'created_at': '2015-07-14T05:22:07.000Z', 'de...",NaN,"[{'id': '1164887035653566464', 'type': 'retwee...",{'attachments': {'media_keys': ['3_11648870285...,NaN,NaN,NaN,NaN,NaN,NaN
27267,2491046567,1212161581670391808,2020-01-01 00:00:16+00:00,[1212161581670391809],"{'annotations': [{'end': 7, 'normalized_text':...",1212161581670391808,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Brooklyn gets first public bike parking hub - ...,"{'created_at': '2014-04-18T01:39:46.000Z', 'de...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Patchogue, NY",NaN

# **GEO-LOcation **

In [ ]:
with pd.option_context('display.max_colwidth', None):
  print(df["geo"])

0                                     NaN
1                                     NaN
2        {'place_id': '488da0de4c92ac8e'}
3                                     NaN
4                                     NaN
                       ...
27263                                 NaN
27264    {'place_id': '2a3a6daaec3b0848'}
27265                                 NaN
27266                                 NaN
27267                                 NaN
Name: geo, Length: 27268, dtype: object

In [ ]:
df["geo"][27236]

{'coordinates': {'coordinates': [-71.68527778, -33.44222222], 'type': 'Point'},
 'place_id': '001bbfee6edcdb06'}

In [ ]:
df['geo'].tail(40)

27228                                                  NaN
27229                                                  NaN
27230                                                  NaN
27231                                                  NaN
27232                                                  NaN
27233                                                  NaN
27234                                                  NaN
27235                                                  NaN
27236    {'coordinates': {'coordinates': [-71.68527778,...
27237                                                  NaN
27238                                                  NaN
27239                                                  NaN
27240                                                  NaN
27241                                                  NaN
27242    {'coordinates': {'coordinates': [-118.55781592...
27243                                                  NaN
27244                     {'place_id': '4bb41f9d86e16416'}
27245                                                  NaN
27246                                                  NaN
27247                                                  NaN
27248                                                  NaN
27249                                                  NaN
27250                                                  NaN
27251                                                  NaN
27252                                                  NaN
27253                                                  NaN
27254                                                  NaN
27255                                                  NaN
27256                                                  NaN
27257                                                  NaN
27258                                                  NaN
27259                                                  NaN
27260                                                  NaN
27261                                                  NaN
27262                                                  NaN
27263                                                  NaN
27264                     {'place_id': '2a3a6daaec3b0848'}
27265                                                  NaN
27266                                                  NaN
27267                                                  NaN
Name: geo, dtype: object

In [ ]:
import re
i=0
df['user_geo']="NaN"
for value in df['geo']:
    if isinstance(value, dict):
      my_string = str(value)
      matches = re.findall(r'\[(.*?)\]', my_string)
      #print(matches.types)
      if not matches:
        df['user_geo'][i] = "NaN"
        i += 1

      else:
        df['user_geo'][i] = str(matches)
        i += 1

<ipython-input-17-a195e7ea4226>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_geo'][i] = "NaN"
<ipython-input-17-a195e7ea4226>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['user_geo'][i] = str(matches)

In [ ]:
df['user_geo']

0                                   NaN
1                 ['-98.4933, 29.4239']
2               ['-98.50385, 29.40534']
3        ['-116.15290175, 43.57641407']
4                                   NaN
                      ...
27263                               NaN
27264                               NaN
27265                               NaN
27266                               NaN
27267                               NaN
Name: user_geo, Length: 27268, dtype: object

In [ ]:
df['New_location']="NaN"
for i in range(n):
  if(df['user_geo'][i]!="NaN"):
    df['New_location'][i] = df['user_geo'][i]
  elif(df['user_geo'][i]=="NaN" and df['twitter_places_nafis'][i]!="NaN"):
    df['New_location'][i] = df['twitter_places_nafis'][i]
  else:
    df['New_location'][i] = df['user_location'][i]

<ipython-input-19-d34ea016d44d>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New_location'][i] = df['user_location'][i]
<ipython-input-19-d34ea016d44d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New_location'][i] = df['user_geo'][i]
<ipython-input-19-d34ea016d44d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New_location'][i] = df['twitter_places_nafis'][i]

In [ ]:
df['New_location'].sample(20)

5876                                                   NaN
5953                                             Ohio, USA
10695                                      Market Weighton
4015                                                 Earth
12969                                      Minneapolis, MN
18712                                          Seattle, WA
2404                                      Leipzig, Germany
1506                                                 india
15296                                                  NaN
9285                                              Virginia
7081                                           Decatur, GA
27077                                                  NaN
8305                                          New York, NY
4152                                                   NaN
9040                                   Ramsey, Isle of Man
19787                                           Isla Sorna
19700                              East Kilbride, Scotland
12530    [-80.369507, 26.0295373, -80.2008709, 26.1268035]
3678                                                   NaN
997                            Tempe, AZ | Dublin, Ireland
Name: New_location, dtype: object

In [ ]:
df['New_location'].value_counts()

NaN                               5662
Washington, DC                     241
Los Angeles, CA                    220
Center Valley, PA                  215
London, England                    215
                                  ...
West Yorkshire, United Kingdom       1
21 ; she!her ; lesbian               1
Kennewick, WA                        1
Abuja  or  Ebonyi                    1
Patchogue, NY                        1
Name: New_location, Length: 8649, dtype: int64

In [ ]:
df

,author_id,conversation_id,created_at,edit_history_tweet_ids,entities,id,lang,public_metrics,text,user,...,referenced_tweets,retweeted_status,geo,twitter_places,attachments,withheld,user_location,twitter_places_nafis,user_geo,New_location
0,22788836,1223395490366025728,2020-01-31 23:59:49+00:00,[1223395490366025728],"{'annotations': [{'end': 7, 'normalized_text':...",1223395490366025728,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Alonso L is starting a bike ride and you can t...,"{'created_at': '2009-03-04T15:44:31.000Z', 'de...",...,NaN,NaN,NaN,NaN,NaN,NaN,"Auckland, New Zealand",NaN,NaN,"Auckland, New Zealand"
1,3157671046,1223383749263593472,2020-01-31 23:59:11+00:00,[1223395330974191617],"{'mentions': [{'end': 12, 'id': '23829152', 's...",1223395330974191616,en,"{'impression_count': 0, 'like_count': 1, 'quot...","@BoycottsBat Few of my mates agree, got to tal...","{'created_at': '2015-04-11T20:24:00.000Z', 'de...",...,"[{'id': '1223387698720911360', 'type': 'replie...","{'author_id': '23829152', 'conversation_id': '...",NaN,NaN,NaN,NaN,"Scotland, United Kingdom",NaN,"['-98.4933, 29.4239']","['-98.4933, 29.4239']"
2,181634813,1223394798876479488,2020-01-31 23:57:04+00:00,[1223394798876479489],"{'annotations': [{'end': 71, 'normalized_text'...",1223394798876479488,en,"{'impression_count': 0, 'like_count': 7, 'quot...",My mamba mentality just got me through a 3 mil...,"{'created_at': '2010-08-22T18:02:25.000Z', 'de...",...,NaN,NaN,{'place_id': '488da0de4c92ac8e'},"{'country': 'United States', 'full_name': 'Pla...",NaN,NaN,"Somewhere making it happen, TX","[-96.85743, 32.9971507, -96.612371, 33.1253341]","['-98.50385, 29.40534']","['-98.50385, 29.40534']"
3,1633428576,1223394344545275904,2020-01-31 23:55:15+00:00,[1223394344545275905],"{'annotations': [{'end': 40, 'normalized_text'...",1223394344545275904,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @BillyCorben: TONIGHT #SuperBowl Miami traf...,"{'created_at': '2013-07-30T17:45:37.000Z', 'de...",...,"[{'id': '1223335486007148546', 'type': 'retwee...",{'attachments': {'media_keys': ['3_12233354821...,NaN,NaN,NaN,NaN,"Coral Springs, FL",NaN,"['-116.15290175, 43.57641407']","['-116.15290175, 43.57641407']"
4,1225992186,1223358325452087296,2020-01-31 23:55:10+00:00,[1223394321560244224],"{'mentions': [{'end': 15, 'id': '58885604', 's...",1223394321560244224,en,"{'impression_count': 0, 'like_count': 0, 'quot...",@originaltomtom @sibilia_ralph @AMarch4OurLive...,"{'created_at': '2013-02-27T20:40:54.000Z', 'de...",...,"[{'id': '1223392333502218240', 'type': 'replie...",NaN,NaN,NaN,NaN,NaN,"Innsmouth, Massachusetts",NaN,NaN,"Innsmouth, Massachusetts"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27263,2612253354,1212163653568540672,2020-01-01 00:08:30+00:00,[1212163653568540674],"{'annotations': [{'end': 83, 'normalized_text'...",1212163653568540672,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @SoBiHamilton: Together we have ridden over...,"{'created_at': '2014-07-08T20:20:50.000Z', 'de...",...,"[{'id': '1212035371808305153', 'type': 'retwee...","{'author_id': '2301638287', 'conversation_id':...",NaN,NaN,NaN,NaN,"Hamilton, Ontario",NaN,NaN,"Hamilton, Ontario"
27264,2221442917,1212163086624247808,2020-01-01 00:06:15+00:00,[1212163086624247808],{'urls': [{'display_url': 'pic.twitter.com/rKr...,1212163086624247808,en,"{'impression_count': 0, 'like_count': 0, 'quot...",üòçüòçüòçüòç2‚É£0‚É£2‚É£0‚É£ first bike ride https://t.co/rKrK...,"{'created_at': '2013-11-29T13:26:39.000Z', 'de...",...,NaN,NaN,{'place_id': '2a3a6daaec3b0848'},"{'country': 'India', 'full_name': 'Sholinganal...",{'media_keys': ['7_1212163009256124416']},NaN,NaN,"[80.056161, 12.850328, 80.268192, 13.028593]",NaN,"[80.056161, 12.850328, 80.268192, 13.028593]"
27265,114743976,1212161757105577984,2020-01-01 00:00:58+00:00,[1212161757105577986],"{'annotations': [{'end': 77, 'normalized_text'...",1212161757105577984,en,"{'impression_count': 0, 'like_count': 1, 'quot...",Should of gone out for a bike ride in the dark...,"{'created_at': '2010-02-16T13:29:12.000Z', 'de...",...,NaN,NaN,NaN,NaN,{'media_keys': ['3_1212161747362168832']},NaN,London Brighton Sussex UK,NaN,NaN,London Brighton Sussex UK
27266,3279247754,1212161708803801088,2020-01-01 00:00:46+00:00,[1212161708803801089],"{'mentions': [{'end': 16, 'id': '1075134579214...",1212161708803801088,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @DomLadMaster: Happy Friday everyone!\n\nTi...,"{'created_at': '2015-07-14T05:22:07.000Z', 'de...",...,"[{'id': '1164887035653566464', 'type': 'retwee...",{'attachments': {'media_keys': ['3_11648870285...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27267,2491046567,1212161581670391808,2020-01-01 00:00:16+00:00,[1212161581670391809],"{'annotations': [{'end': 7, 'normalized_text':...",1212161581670391808,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Brooklyn gets first public bike parking hub - ...,"{'created_at': '2014-04-18T01:39:46.000Z', 'de...",...,NaN,NaN,NaN,NaN,NaN,NaN,"Patchogue, NY",NaN,NaN,"Patchogue, NY"

In [ ]:
df['New_location']

0                               Auckland, New Zealand
1                               ['-98.4933, 29.4239']
2                             ['-98.50385, 29.40534']
3                      ['-116.15290175, 43.57641407']
4                            Innsmouth, Massachusetts
                             ...
27263                               Hamilton, Ontario
27264    [80.056161, 12.850328, 80.268192, 13.028593]
27265                       London Brighton Sussex UK
27266                                             NaN
27267                                   Patchogue, NY
Name: New_location, Length: 27268, dtype: object

In [ ]:
df.head(10)

,author_id,conversation_id,created_at,edit_history_tweet_ids,entities,id,lang,public_metrics,text,user,...,referenced_tweets,retweeted_status,geo,twitter_places,attachments,withheld,user_location,twitter_places_nafis,user_geo,New_location
0,22788836,1223395490366025728,2020-01-31 23:59:49+00:00,[1223395490366025728],"{'annotations': [{'end': 7, 'normalized_text':...",1223395490366025728,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Alonso L is starting a bike ride and you can t...,"{'created_at': '2009-03-04T15:44:31.000Z', 'de...",...,NaN,NaN,NaN,NaN,NaN,NaN,"Auckland, New Zealand",NaN,NaN,"Auckland, New Zealand"
1,3157671046,1223383749263593472,2020-01-31 23:59:11+00:00,[1223395330974191617],"{'mentions': [{'end': 12, 'id': '23829152', 's...",1223395330974191616,en,"{'impression_count': 0, 'like_count': 1, 'quot...","@BoycottsBat Few of my mates agree, got to tal...","{'created_at': '2015-04-11T20:24:00.000Z', 'de...",...,"[{'id': '1223387698720911360', 'type': 'replie...","{'author_id': '23829152', 'conversation_id': '...",NaN,NaN,NaN,NaN,"Scotland, United Kingdom",NaN,"['-98.4933, 29.4239']","['-98.4933, 29.4239']"
2,181634813,1223394798876479488,2020-01-31 23:57:04+00:00,[1223394798876479489],"{'annotations': [{'end': 71, 'normalized_text'...",1223394798876479488,en,"{'impression_count': 0, 'like_count': 7, 'quot...",My mamba mentality just got me through a 3 mil...,"{'created_at': '2010-08-22T18:02:25.000Z', 'de...",...,NaN,NaN,{'place_id': '488da0de4c92ac8e'},"{'country': 'United States', 'full_name': 'Pla...",NaN,NaN,"Somewhere making it happen, TX","[-96.85743, 32.9971507, -96.612371, 33.1253341]","['-98.50385, 29.40534']","['-98.50385, 29.40534']"
3,1633428576,1223394344545275904,2020-01-31 23:55:15+00:00,[1223394344545275905],"{'annotations': [{'end': 40, 'normalized_text'...",1223394344545275904,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @BillyCorben: TONIGHT #SuperBowl Miami traf...,"{'created_at': '2013-07-30T17:45:37.000Z', 'de...",...,"[{'id': '1223335486007148546', 'type': 'retwee...",{'attachments': {'media_keys': ['3_12233354821...,NaN,NaN,NaN,NaN,"Coral Springs, FL",NaN,"['-116.15290175, 43.57641407']","['-116.15290175, 43.57641407']"
4,1225992186,1223358325452087296,2020-01-31 23:55:10+00:00,[1223394321560244224],"{'mentions': [{'end': 15, 'id': '58885604', 's...",1223394321560244224,en,"{'impression_count': 0, 'like_count': 0, 'quot...",@originaltomtom @sibilia_ralph @AMarch4OurLive...,"{'created_at': '2013-02-27T20:40:54.000Z', 'de...",...,"[{'id': '1223392333502218240', 'type': 'replie...",NaN,NaN,NaN,NaN,NaN,"Innsmouth, Massachusetts",NaN,NaN,"Innsmouth, Massachusetts"
5,378517016,1223394253562351616,2020-01-31 23:54:54+00:00,[1223394253562351616],"{'urls': [{'display_url': 'lnkd.in/egafuTx', '...",1223394253562351616,en,"{'impression_count': 0, 'like_count': 0, 'quot...",Be grateful for what you have. This cyclist ro...,"{'created_at': '2011-09-23T10:26:34.000Z', 'de...",...,NaN,NaN,NaN,NaN,NaN,NaN,MoDOT,NaN,NaN,MoDOT
6,1960044362,1223391099764559872,2020-01-31 23:42:22+00:00,[1223391099764559874],"{'annotations': [{'end': 112, 'normalized_text...",1223391099764559872,en,"{'impression_count': 0, 'like_count': 0, 'quot...",RT @future_crunch: Following improvements in c...,"{'created_at': '2013-10-14T06:14:07.000Z', 'de...",...,"[{'id': '1223274497811283968', 'type': 'retwee...",{'attachments': {'media_keys': ['3_12232744958...,NaN,NaN,NaN,NaN,NaN,NaN,"['-77.34409, 34.7257']","['-77.34409, 34.7257']"
7,518046429,1223390232827043840,2020-01-31 23:38:55+00:00,[1223390232827043840],"{'annotations': [{'end': 80, 'normalized_text'...",1223390232827043840,en,"{'impression_count': 0, 'like_count': 13, 'quo...",Wondering where the new @BikeShareTO stations ...,"{'created_at': '2012-03-08T00:03:22.000Z', 'de...",...,NaN,NaN,NaN,NaN,NaN,NaN,Toronto,NaN,NaN,Toronto
8,1215591528531259392,1223389935484301312,2020-01-31 23:37:46+00:00,[1223389941721251840],"{'annotations': [{'end': 38, 'normalized_text'...",1223389941721251840,en,"{'impression_count': 0, 'like_count': 0, 'quot...",‚Ä¢bowling\n‚Ä¢boxing\n‚Ä¢football \n‚Ä¢trampoline \n‚Ä¢...,"{'created_at': '2020-01-10T11:09:46.000Z', 'de...",...,"[{'id': '1223389938726494208', 'type': 'replie...","{'author_id': '1215591528531259392', 'conversa...",NaN,NaN,NaN,NaN,Neverland,NaN,"['-2.67776728, 53.22910825']","['-2.67776728, 53.22910825']"
9,3379003163,1150073652374728704,2020-01-31 23:37:29+00:00,[1223389872137932809],"{'annotations': [{'end': 126, 'normalized_text...",1223389872137932800,en,"{'impression_count': 0, 'like_count': 2, 'quot...",@x3nome It was so nice to finally meet you on ...,"{'created_at': '2015-07-16T16:37:38.000Z', 'de...",...,"[{'id': '1223368976132034560', 'type': 'replie...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['-122.42554961, 37.770113190000004']","['-122.42554961, 37.770113190000004']"

In [ ]:
df1 = df.drop(['author_id',  'in_reply_to_user_id' ,'lang' , 'conversation_id', 'created_at', 'edit_history_tweet_ids', 'entities', 'id', 'public_metrics', 'user',  'referenced_tweets', 'retweeted_status', 'geo', 'twitter_places', 'attachments', 'withheld'], axis=1)

In [ ]:
df1.rename(columns = {'text':'Tweet', 'twitter_places_nafis':'Twitter_Place',
                              'geocoordinates':'Geo_Code'}, inplace = True)

In [ ]:
df1.head(10)

,Tweet,user_location,Twitter_Place,user_geo,New_location
0,Alonso L is starting a bike ride and you can t...,"Auckland, New Zealand",NaN,NaN,"Auckland, New Zealand"
1,"@BoycottsBat Few of my mates agree, got to tal...","Scotland, United Kingdom",NaN,"['-98.4933, 29.4239']","['-98.4933, 29.4239']"
2,My mamba mentality just got me through a 3 mil...,"Somewhere making it happen, TX","[-96.85743, 32.9971507, -96.612371, 33.1253341]","['-98.50385, 29.40534']","['-98.50385, 29.40534']"
3,RT @BillyCorben: TONIGHT #SuperBowl Miami traf...,"Coral Springs, FL",NaN,"['-116.15290175, 43.57641407']","['-116.15290175, 43.57641407']"
4,@originaltomtom @sibilia_ralph @AMarch4OurLive...,"Innsmouth, Massachusetts",NaN,NaN,"Innsmouth, Massachusetts"
5,Be grateful for what you have. This cyclist ro...,MoDOT,NaN,NaN,MoDOT
6,RT @future_crunch: Following improvements in c...,NaN,NaN,"['-77.34409, 34.7257']","['-77.34409, 34.7257']"
7,Wondering where the new @BikeShareTO stations ...,Toronto,NaN,NaN,Toronto
8,‚Ä¢bowling\n‚Ä¢boxing\n‚Ä¢football \n‚Ä¢trampoline \n‚Ä¢...,Neverland,NaN,"['-2.67776728, 53.22910825']","['-2.67776728, 53.22910825']"
9,@x3nome It was so nice to finally meet you on ...,NaN,NaN,"['-122.42554961, 37.770113190000004']","['-122.42554961, 37.770113190000004']"

Now it time to Geoparse and install **Mordecai**

In [ ]:
!pip install -q https://github.com/ac74475/mordecai/archive/refs/heads/performance-improvement.zip
#pip install mordecai
!pip install -q spacy==3.4.0
!pip install -q srsly==2.4.0

     / 1.2 MB 4.3 MB/s 0:00:00
  Preparing metadata (setup.py) ... done
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 58.7/58.7 kB 1.4 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 46.7/46.7 kB 4.0 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 4.9/4.9 MB 47.2 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 143.1/143.1 kB 15.5 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 1.0/1.0 MB 57.8 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 369.2/369.2 kB 33.1 MB/s eta 0:00:00
  Building wheel for mordecai (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
confection 0.1.1 requires srsly<3.0.0,>=2.4.0, but you have srsly 1.0.7 which is incompatible.
en-core-web-sm 3.6.0 requires spacy<3.7.0,>=3.6.0, but you have spacy 2.3.9 which is incompatible.
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 6.4/6.4 MB 5.9 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 919.6/919.6 kB 23.5 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 492.9/492.9 kB 21.0 MB/s eta 0:00:00
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 12.0/12.0 MB 15.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
en-core-web-sm 3.6.0 requires spacy<3.7.0,>=3.6.0, but you have spacy 3.4.0 which is incompatible.
mordecai 2.1.0 requires spacy<3.0,>=2.3, but you have spacy 3.4.0 which is incompatible.
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 314.7/314.7 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  √ó Getting requirements to build wheel did not run successfully.
  ‚îÇ exit code: 1
  ‚ï∞‚îÄ> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

√ó Getting requirements to build wheel did not run successfully.
‚îÇ exit code: 1
‚ï∞‚îÄ> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [ ]:
!python -m spacy download en_core_web_lg

2023-08-30 01:38:26.772350: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-30 01:38:27.893620: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEPRECATION: https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.4.1/en_core_web_lg-3.4.1-py3-none-any.whl#egg=en_core_web_lg==3.4.1 contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617
Collecting en-core-web-lg==3.4.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.4.1/en_core_web_lg-3.4.1-py3-none-any.whl (587.7 MB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 587.7/587.7 MB 2.5 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.5.0,>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from en-core-web-lg==3.4.1) (3.4.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (8.1.12)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (0.10.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (2.4.7)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (2.0.9)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (0.4.2)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (0.10.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (4.66.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (1.23.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (1.9.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (23.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (3.3.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from pathy>=0.3.5->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (6.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (2023.7.22)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (0.7.10)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (0.1.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.5.0,>=0.3.0->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.5.0,>=3.4.0->en-core-web-lg==3.4.1) (2.1.3)
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.4.1
‚úî Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [ ]:
!sed -i 's/collections.Mapping/collections.abc.Mapping/g' /usr/local/lib/python3.10/dist-packages/elasticsearch_dsl/search.py
!sed -i 's/collections.Mapping/collections.abc.Mapping/g' /usr/local/lib/python3.10/dist-packages/elasticsearch_dsl/query.py
!sed -i 's/collections.Mapping/collections.abc.Mapping/g' /usr/local/lib/python3.10/dist-packages/elasticsearch_dsl/utils.py

In [ ]:
!wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.2.tar.gz -q
!tar -xzf elasticsearch-5.5.2.tar.gz
!wget https://andrewhalterman.com/files/geonames_index.tar.gz --output-file=wget_log.txt
!tar -xzf geonames_index.tar.gz
!mkdir /content/elasticsearch-5.5.2/data
!mv geonames_index/* /content/elasticsearch-5.5.2/data
!sudo chown -R daemon:daemon elasticsearch-5.5.2/

In [ ]:
import subprocess
bashCommand = "sudo -H -u daemon elasticsearch-5.5.2/bin/elasticsearch"
subprocess.Popen(bashCommand.split())

In [ ]:
# Sleep for few seconds to let the instance start.
import time
time.sleep(20)

In [ ]:
# check if it is running
!ps -ef | grep elasticsearch

root        2738     153  0 01:43 ?        00:00:00 sudo -H -u daemon elasticsearch-5.5.2/bin/elasticsearch
daemon      2739    2738 13 01:43 ?        00:00:19 /bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/content/elasticsearch-5.5.2 -cp /content/elasticsearch-5.5.2/lib/* org.elasticsearch.bootstrap.Elasticsearch
root        3419     153  0 01:46 ?        00:00:00 /bin/bash -c ps -ef | grep elasticsearch
root        3421    3419  0 01:46 ?        00:00:00 grep elasticsearch

# **GeoParse Interface**

In [ ]:
from mordecai import Geoparser
geo = Geoparser()

Models path: /usr/local/lib/python3.10/dist-packages/mordecai/models/

In [ ]:
from tqdm import tqdm
import pandas as pd
geonames = geo.geoparse("I traveled from Colorado to Ottawa.")

print(geonames)

/usr/local/lib/python3.10/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)

1/1 [==============================] - 0s 304ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 90ms/step
[{'word': 'Colorado', 'spans': [{'start': 16, 'end': 24}], 'country_predicted': 'CRI', 'country_conf': 0.19161285}, {'word': 'Ottawa', 'spans': [{'start': 28, 'end': 34}], 'country_predicted': 'CAN', 'country_conf': 0.94244355, 'geo': {'admin1': 'Ontario', 'lat': '45.41117', 'lon': '-75.69812', 'country_code3': 'CAN', 'geonameid': '6094817', 'place_name': 'Ottawa', 'feature_class': 'P', 'feature_code': 'PPLC'}}]

In [ ]:
df1

,Tweet,user_location,Twitter_Place,user_geo,New_location
0,Alonso L is starting a bike ride and you can t...,"Auckland, New Zealand",NaN,NaN,"Auckland, New Zealand"
1,"@BoycottsBat Few of my mates agree, got to tal...","Scotland, United Kingdom",NaN,"['-98.4933, 29.4239']","['-98.4933, 29.4239']"
2,My mamba mentality just got me through a 3 mil...,"Somewhere making it happen, TX","[-96.85743, 32.9971507, -96.612371, 33.1253341]","['-98.50385, 29.40534']","['-98.50385, 29.40534']"
3,RT @BillyCorben: TONIGHT #SuperBowl Miami traf...,"Coral Springs, FL",NaN,"['-116.15290175, 43.57641407']","['-116.15290175, 43.57641407']"
4,@originaltomtom @sibilia_ralph @AMarch4OurLive...,"Innsmouth, Massachusetts",NaN,NaN,"Innsmouth, Massachusetts"
...,...,...,...,...,...
27263,RT @SoBiHamilton: Together we have ridden over...,"Hamilton, Ontario",NaN,NaN,"Hamilton, Ontario"
27264,üòçüòçüòçüòç2‚É£0‚É£2‚É£0‚É£ first bike ride https://t.co/rKrK...,NaN,"[80.056161, 12.850328, 80.268192, 13.028593]",NaN,"[80.056161, 12.850328, 80.268192, 13.028593]"
27265,Should of gone out for a bike ride in the dark...,London Brighton Sussex UK,NaN,NaN,London Brighton Sussex UK
27266,RT @DomLadMaster: Happy Friday everyone!\n\nTi...,NaN,NaN,NaN,NaN
27267,Brooklyn gets first public bike parking hub - ...,"Patchogue, NY",NaN,NaN,"Patchogue, NY"

Lets Start the **Naughty** Game

In [ ]:
import multiprocessing as mp
import os
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
from geopy.distance import great_circle as GRC
from mordecai import Geoparser
from dask.distributed import Client, progress
import dask.dataframe as dd
from multiprocessing.pool import ThreadPool as Pool

In [ ]:
geolocator = Nominatim(user_agent='my_geocoder')

In [ ]:
def geoparse_location(location):
    try:
        location_data = geo.geoparse(location)
        if location_data:
            return location_data
        else:
            return None
    except GeocoderTimedOut:
        return geoparse_location(location)


def reverse_geoparse_coordinates(lat_long):
    try:
        location_data = geolocator.reverse(lat_long, timeout=10)
        if location_data:
            return location_data
        else:
            return None
    except GeocoderTimedOut:
        return reverse_geoparse_coordinates(lat_long)




def parsingFunction(df):
    # Iterate over each row in the DataFrame without using index
    for index, row in df.iterrows():
        location = row['New_location']
        # Check if the location is a city name or coordinates
        if pd.isnull(location):
            continue
        if "['" in location:
            # Reverse geoparse coordinates
            split_string = location.split(',')
            listSize = len(split_string)

            if listSize == 2:
                lat = split_string[1].strip("']")
                long = split_string[0].strip("['")

                location_data = reverse_geoparse_coordinates((lat, long))

            if listSize == 4:
                # print("list size = 4: ")
                # print(listSize)
                lon1 = split_string[0][2:]
                lat1 = split_string[1]
                lon2 = split_string[2]
                lat2 = split_string[3][:-2]

                coord1 = lat1 + "," + lon1
                coord2 = lat2 + "," + lon2

                distance = GRC(coord1, coord2).km
                # print(distance)
                if distance <= 200:
                    latitude = (float(lat1) + float(lat2)) / 2
                    longitude = (float(lon1) + float(lon2)) / 2

                    coordinates = (latitude, longitude)
                    # print("four: ")
                    # print(coordinates)
                    location_data = reverse_geoparse_coordinates(coordinates)
                else:
                    location = row['user_location']
                    if pd.isnull(location):
                        pass
            # Extract country, state, latitude, and longitude from the geocoded/reverse geocoded location
            if location_data:
                address = location_data.raw.get('address', {})
                df.at[index, 'Country_conf'] = 99
                df.at[index, 'Country'] = address.get('country', '')
                df.at[index, 'State'] = address.get('state', '')
                df.at[index, 'City'] = address.get('city', '')
                df.at[index, 'Latitude'] = location_data.latitude
                df.at[index, 'Longitude'] = location_data.longitude
        else:
            # Geoparse city name
            geonames = geoparse_location(location)
            if geonames is None:
                geonames = {}
            my_dict = {key: value for key, value in enumerate(geonames)}

            if my_dict is None:
                my_dict = {}

            for key in my_dict.keys():
                value = my_dict[key]
                df.at[index, 'Country_conf'] = value['country_conf']
                df.at[index, 'Country'] = value['country_predicted']
                df.at[index, 'City'] = value['word']
                column_name = 'geo'
                if column_name in value:
                    df.at[index, 'State'] = value['geo']['admin1']
                    df.at[index, 'Latitude'] = value['geo']['lat']
                    df.at[index, 'Longitude'] = value['geo']['lon']
    return df

**Main Function**

In [ ]:
if __name__ == '__main__':
    # df = pd.read_csv("E:\Tweet\Dav\Processed_data_Sample\Davnet.csv")
    # Create empty columns for country, state, latitude, and longitude
    df1['Country_conf'] = ''
    df1['Country'] = ''
    df1['State'] = ''
    df1['City'] = ''
    df1['Latitude'] = ''
    df1['Longitude'] = ''

    num_chunks = mp.cpu_count()
    df_split = np.array_split(df1, num_chunks)
    pool = mp.Pool()
    pool.map_async(parsingFunction, df_split)

    pool.close()
    pool.join()

    # df_processed = pd.concat(df_split)

/usr/local/lib/python3.10/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)
/usr/local/lib/python3.10/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)

normal

In [ ]:
if __name__ == '__main__':
    # df = pd.read_csv("E:\Tweet\Dav\Processed_data_Sample\Tweetpie_main_00.csv")
    #     # Create empty columns for country, state, latitude, and longitude
    df1['Country_conf'] = ''
    df1['Country'] = ''
    df1['State'] = ''
    df1['City'] = ''
    df1['Latitude'] = ''
    df1['Longitude'] = ''

    df_processed = parsingFunction(df1)

    #os.makedirs("E:\Tweet\Dav\Processed_data_Sample", exist_ok=True)
    #df_processed.to_csv("E:\Tweet\Dav\Processed_data_Sample\Davnet8.csv")

1/1 [==============================] - 0s 32ms/step

/usr/local/lib/python3.10/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)

1/1 [==============================] - 0s 33ms/step

WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.004s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b801be43e50>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8029f7c760>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8023e3a170>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8023e39cc0>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.009s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8023e38d90>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8023e254b0>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7b8023e393c0>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:GET http://localhost:9200/geonames/_search [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request

ConnectionError: ignored

In [ ]:
df_processed

NameError: ignored